DROP TABLE IF EXISTS `sqlmap`;
CREATE TABLE `sqlmap` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`url` VARCHAR(2048) DEFAULT NULL,
	`num` VARCHAR(255) DEFAULT NULL,
	`dbms` VARCHAR(255) DEFAULT NULL,
	`dbms_version` VARCHAR(255) DEFAULT NULL,
	`matchRatio` FLOAT DEFAULT NULL,
	`payload` LONGTEXT,
	`title` VARCHAR(255) DEFAULT NULL,
	`vector` VARCHAR(255) DEFAULT NULL,
	`request_text` LONGTEXT,
	ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `xsser`;
CREATE TABLE `xsser` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`url` VARCHAR(2048) DEFAULT NULL,
	`target` VARCHAR(255) DEFAULT NULL,
	`injection` VARCHAR(255) DEFAULT NULL,
	`method` VARCHAR(255) DEFAULT NULL,
	`special` VARCHAR(255) DEFAULT NULL,
	`browsers` VARCHAR(255) DEFAULT NULL,
	`final_attack` LONGTEXT,
	ctime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `redirect`;
CREATE TABLE `redirect` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` longtext,
  `payload` longtext,
  `method` varchar(255) DEFAULT NULL,
  ctime timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;